# Build this django app as a python package
# and upload it to our package registry/repo.

default:
  image: python

# Most variables are predefined.
# See https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
variables:
  # CI_API_V4_URL: The GitLab API v4 root URL.
  # CI_PROJECT_ID: The ID of the current project.
  # This ID is unique across all projects on the GitLab instance.
  # Project 60 is *OMlPI*
  # Open Medialab Package Index - a public repository of software for our packages
  PACKAGE_REGISTRY_PROJECT_ID: 60
  TWINE_PASSWORD: ${CI_JOB_TOKEN}
  TWINE_USERNAME: "gitlab-ci-token"

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - python setup.py sdist bdist_wheel
    - pip install twine
    - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${PACKAGE_REGISTRY_PROJECT_ID}/packages/pypi dist/*
    - echo "Package successfully published."
